# Python CircleCI 2.0 configuration file
verson: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      # Step 1: Obtain repo from github
      - checkout
      # Step 2: Create venv and install dependencies
      - run:
          name: install dependencies
          command:
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
      # Step 3: Run linter and tests
      - run:
          name: run tests
          command:
            . venv/bin/activate
            flake8 --exclude=venv  --statistics
            pytest -v --cov